title: Sweets, Shoes, and Sass
author: Jeanie V. 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a basic twenty-something year old's take on a blog. As the title suggests, I bake sweets, I buy shoes, and I have sass. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
